/**
 * HAU-1 / draft / target_release_at: null
 * 목적: 기존 4.2 병원 웹 스타일을 유지한 커넥트 통합 업무 시뮬레이터.
 * As-is: 기존 진료항목 예약 3탭·진료항목·운영 설정. To-be는 명시적으로 켠 경우만 표시.
 * 모든 정보는 가상 데이터이며 브라우저 메모리에서만 변경됨. 서버·차트·설치·알림 통신 없음.
 * 차트 전달은 확인된 취소/내원 이벤트만 모사. 진료완료 차트 규격은 미확정으로 보류.
 */
import React, { useEffect, useRef, useState } from 'react';
import { VscChevronDown, VscChevronRight, VscChromeMinimize, VscChromeMaximize, VscChromeRestore, VscChromeClose, VscSettingsGear, VscSearch, VscRefresh, VscCheck, VscBell, VscHistory, VscDashboard, VscListFlat, VscVm as VscDeviceDesktop, VscWarning, VscDebugDisconnect, VscAdd, VscArrowRight, VscInfo, VscCalendar } from 'react-icons/vsc';

const LOGO = require('../../../assets/curation-price/goodoc-logo.svg');
type Kind = '접수' | '진료실 예약' | '진료항목 예약';
type State = '확정대기' | '내원예정' | '진료대기중' | '병원취소' | '환자취소' | '예약실패' | '진료완료' | '자동 종료';
type RecordItem = { id: string; kind: Kind; name: string; phone: string; time: string; date: string; room: string; item: string; price: string; state: State; reason?: string; delivery?: string };
const TODAY = '2026-10-02';
const BASE: RecordItem[] = [
  { id:'R001', kind:'접수', name:'김○○', phone:'010-****-1001', date:TODAY, time:'09:10', room:'1진료실', item:'일반 진료', price:'—', state:'진료대기중' },
  { id:'S002', kind:'진료실 예약', name:'박○○', phone:'010-****-1002', date:TODAY, time:'10:30', room:'2진료실', item:'내과 진료', price:'—', state:'내원예정' },
  { id:'T003', kind:'진료항목 예약', name:'이○○', phone:'010-****-1003', date:TODAY, time:'11:00', room:'—', item:'독감 백신 · 방문 후 결정', price:'미정', state:'확정대기' },
  { id:'T004', kind:'진료항목 예약', name:'최○○', phone:'010-****-1004', date:TODAY, time:'11:30', room:'—', item:'가다실 9가 · 1회', price:'210,000원', state:'내원예정' },
  { id:'R005', kind:'접수', name:'정○○', phone:'010-****-1005', date:TODAY, time:'09:20', room:'1진료실', item:'일반 진료', price:'—', state:'진료대기중' },
  { id:'S006', kind:'진료실 예약', name:'한○○', phone:'010-****-1006', date:TODAY, time:'12:00', room:'2진료실', item:'내과 진료', price:'—', state:'예약실패', reason:'차트 응답을 확인하지 못했습니다.' },
  { id:'S007', kind:'진료실 예약', name:'조○○', phone:'010-****-1007', date:TODAY, time:'14:00', room:'1진료실', item:'가정의학과 진료', price:'—', state:'확정대기' },
  { id:'T008', kind:'진료항목 예약', name:'윤○○', phone:'010-****-1008', date:TODAY, time:'14:30', room:'—', item:'싱그릭스 · 1회', price:'230,000원', state:'내원예정' },
  { id:'R009', kind:'접수', name:'장○○', phone:'010-****-1009', date:TODAY, time:'08:50', room:'2진료실', item:'내과 진료', price:'—', state:'진료완료' },
  { id:'S010', kind:'진료실 예약', name:'임○○', phone:'010-****-1010', date:TODAY, time:'09:00', room:'1진료실', item:'일반 진료', price:'—', state:'병원취소', reason:'담당 의료진 부재' },
  { id:'T011', kind:'진료항목 예약', name:'오○○', phone:'010-****-1011', date:TODAY, time:'15:00', room:'—', item:'독감 백신 · 방문 후 결정', price:'미정', state:'환자취소' },
  { id:'T012', kind:'진료항목 예약', name:'송○○', phone:'010-****-1012', date:TODAY, time:'09:30', room:'—', item:'가다실 9가 · 1회', price:'210,000원', state:'진료완료' },
  { id:'R013', kind:'접수', name:'강○○', phone:'010-****-1013', date:TODAY, time:'10:00', room:'1진료실', item:'일반 진료', price:'—', state:'내원예정' },
  { id:'T014', kind:'진료항목 예약', name:'신○○', phone:'010-****-1014', date:'2026-10-03', time:'10:30', room:'—', item:'독감 백신 · 1회', price:'35,000원', state:'내원예정' },
  { id:'T015', kind:'진료항목 예약', name:'유○○', phone:'010-****-1015', date:'2026-09-29', time:'15:00', room:'—', item:'가다실 9가 · 1회', price:'210,000원', state:'자동 종료', reason:'방문 예정일이 지났으며 실제 결과가 확인되지 않았습니다.' },
  { id:'R016', kind:'접수', name:'권○○', phone:'010-****-1016', date:TODAY, time:'10:10', room:'2진료실', item:'내과 진료', price:'—', state:'진료대기중' },
  { id:'T017', kind:'진료항목 예약', name:'안○○', phone:'010-****-1017', date:TODAY, time:'16:00', room:'—', item:'독감 백신 · 1회', price:'35,000원', state:'확정대기' },
  { id:'T018', kind:'진료항목 예약', name:'서○○', phone:'010-****-1018', date:TODAY, time:'13:30', room:'—', item:'가다실 9가 · 1회', price:'210,000원', state:'병원취소', reason:'일정 불가' },
];
const REASONS = ['일정 불가','담당 의료진 부재','진료항목 확인 필요','환자 정보 확인 필요','기타 병원 사정'];
const STATES: State[] = ['내원예정','진료대기중','병원취소','환자취소','예약실패','진료완료'];
const NAV = ['대시보드','진료 현황','진료실 관리','진료항목','진료실 운영 설정'];
const PAST: State[] = ['병원취소','환자취소','진료완료','자동 종료'];
const MUTABLE: State[] = ['내원예정','진료대기중','확정대기','예약실패'];
const STATE_CLASS: Record<State,string> = {'확정대기':'orange','내원예정':'blue','진료대기중':'blue','병원취소':'red','환자취소':'red','예약실패':'orange','진료완료':'green','자동 종료':'gray'};
type Log = { id:number; record:string; action:string; goodoc:string; chart:string; patient:string; pending:boolean };
type Dialog = { type:'detail'|'cancel'|'action'|'settings'|'notice'|'room'|'item'|'guide'; id?:string; action?:'arrival'|'complete'|'confirm'; title?:string; index?:number };

function Tag({state}:{state:State}) { return <span className={'cu-tag '+STATE_CLASS[state]}>{state}</span>; }
function Modal({title,children,footer,onClose,wide=false,busy=false}:{title:string;children:React.ReactNode;footer?:React.ReactNode;onClose:()=>void;wide?:boolean;busy?:boolean}) {
  const ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement; ref.current?.focus(); const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)onClose(); if(e.key==='Tab'){const list=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,textarea,[tabindex="0"]'); if(!list?.length)return; const first=list[0],last=list[list.length-1]; if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}; document.addEventListener('keydown',handler); return ()=>{document.removeEventListener('keydown',handler);previous?.focus();};},[busy]);
  return <div className="cu-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose();}}><div ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} className={'cu-modal '+(wide?'wide':'')}><header><h2>{title}</h2><button className="cu-icon" aria-label="닫기" disabled={busy} onClick={onClose}><VscChromeClose/></button></header><div className="cu-modal-body">{children}</div>{footer&&<footer>{footer}</footer>}</div></div>;
}

export default function Page(){
  const [toBe,setToBe]=useState(false),[menu,setMenu]=useState('진료 현황'),[rows,setRows]=useState(BASE.map(x=>({...x})));
  const [tab,setTab]=useState('예약 신청'),[search,setSearch]=useState(''),[kind,setKind]=useState('전체 유형'),[room,setRoom]=useState('전체 진료실'),[date,setDate]=useState('전체 기간'),[sort,setSort]=useState('가까운 방문일시 순'),[page,setPage]=useState(1);
  const [dialog,setDialog]=useState<Dialog|null>(null),[reason,setReason]=useState(REASONS[0]),[memo,setMemo]=useState(''),[busy,setBusy]=useState(false),[failure,setFailure]=useState(false),[error,setError]=useState('');
  const [linked,setLinked]=useState(false),[chart,setChart]=useState('K차트'),[bridge,setBridge]=useState(false),[online,setOnline]=useState(true),[installing,setInstalling]=useState(false),[serverDown,setServerDown]=useState(false),[tray,setTray]=useState(false),[maximized,setMaximized]=useState(false),[closed,setClosed]=useState(false);
  const [logs,setLogs]=useState<Log[]>([]),[showLogs,setShowLogs]=useState(false),[toast,setToast]=useState('');
  const [rooms,setRooms]=useState([{name:'1진료실',doctor:'김○○ 원장',active:true},{name:'2진료실',doctor:'박○○ 원장',active:true}]);
  const [items,setItems]=useState([{name:'독감 백신',price:'35,000원',category:'예방접종',active:true},{name:'가다실 9가',price:'210,000원',category:'예방접종',active:true},{name:'싱그릭스',price:'230,000원',category:'예방접종',active:true}]);
  const [autoConfirm,setAutoConfirm]=useState(false),[smart,setSmart]=useState(true),[interval,setIntervalValue]=useState('30'),[formName,setFormName]=useState(''),[formPrice,setFormPrice]=useState(''),[formDoctor,setFormDoctor]=useState('');
  const [apptUsed,setApptUsed]=useState(true),[sameDay,setSameDay]=useState(true),[newNotice,setNewNotice]=useState(true);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(timer);},[toast]);
  useEffect(()=>setPage(1),[tab,search,kind,room,date,sort,toBe]);
  const notify=(text:string)=>setToast(text);
  const changeMode=(value:boolean)=>{setToBe(value);setMenu(value?'대시보드':'진료 현황');setTab(value?'전체':'예약 신청');setSearch('');setKind('전체 유형');setRoom('전체 진료실');setDate('전체 기간');setStateFilter('전체 상태');setDialog(null);setTray(false);};
  const go=(name:string,nextTab='전체')=>{setMenu(name);setTab(toBe?nextTab:'예약 신청');setSearch('');setKind('전체 유형');setRoom('전체 진료실');setDate('전체 기간');setStateFilter('전체 상태');};
  const chosen=dialog?.id?rows.find(r=>r.id===dialog.id):undefined;
  const source=rows.filter(r=>toBe||r.kind==='진료항목 예약');
  const inTab=(r:RecordItem,t:string)=>t==='전체'||(t==='처리 필요'?['확정대기','예약실패'].includes(r.state):t==='지난 내역'?PAST.includes(r.state):t==='예약 신청'?r.state==='확정대기':t==='내원 예정'?r.state==='내원예정':t==='진료 대기'?r.state==='진료대기중':r.state===t);
  const tabs=toBe?['전체','내원 예정','진료 대기','처리 필요','지난 내역']:['예약 신청','내원 예정','지난 내역'];
  const [stateFilter,setStateFilter]=useState('전체 상태');
  const list=source.filter(r=>inTab(r,tab)&&(kind==='전체 유형'||(kind==='예약 전체'?r.kind!=='접수':r.kind===kind))&&(room==='전체 진료실'||r.room===room)&&(date==='전체 기간'||r.date===TODAY)&&(stateFilter==='전체 상태'||!toBe||r.state===stateFilter)&&(!search||`${r.name}${r.phone}${r.item}${r.id}`.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>sort==='환자명 순'?a.name.localeCompare(b.name):sort==='최근 방문일시 순'?`${b.date}${b.time}`.localeCompare(`${a.date}${a.time}`):`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`));
  const pageCount=Math.max(1,Math.ceil(list.length/7)),currentPage=Math.min(page,pageCount);
  const clearFilters=()=>{setSearch('');setKind('전체 유형');setRoom('전체 진료실');setStateFilter('전체 상태');setDate('전체 기간');setSort('가까운 방문일시 순');};
  const openCancel=(r:RecordItem)=>{setReason(REASONS[0]);setMemo('');setError('');setDialog({type:'cancel',id:r.id});};
  const action=(r:RecordItem,name:'arrival'|'complete'|'confirm')=>{setError('');setDialog({type:'action',id:r.id,action:name});};
  const execute=async()=>{
    if(!chosen||busy)return;
    if(serverDown){setError('굿닥 서버에 연결할 수 없습니다. 입력 내용은 유지됩니다. 연결을 복구한 후 다시 시도해 주세요.');return;}
    if(dialog?.type==='cancel'&&reason==='직접 입력'&&!memo.trim()){setError('취소 사유를 입력해 주세요.');return;}
    const r=chosen,act=dialog?.type==='cancel'?'cancel':dialog?.action;setBusy(true);setError('');
    await new Promise(resolve=>setTimeout(resolve,500));
    if(failure){setFailure(false);setBusy(false);setError('모의 저장 실패입니다. 상태는 변경되지 않았습니다. 다시 시도할 수 있습니다.');return;}
    const state:State=act==='cancel'?'병원취소':act==='complete'?'진료완료':act==='arrival'?'진료대기중':'내원예정';
    const chartRequired=toBe&&linked&&r.kind!=='진료항목 예약';
    const supported=act==='cancel'||act==='arrival';
    const pending=chartRequired&&supported&&(!bridge||!online);
    const chartResult=!chartRequired?'해당 없음':!supported?'규격 확인 필요 · 요청 보류':pending?'전달 대기 · 연결 복구 필요':'전달·응답 확인 (모의)';
    const finalReason=act==='cancel'?(reason==='직접 입력'?memo.trim():reason):r.reason;
    setRows(old=>old.map(x=>x.id===r.id?{...x,state,reason:finalReason,delivery:chartResult}:x));
    setLogs(old=>[{id:Date.now(),record:r.id,action:act==='cancel'?'병원취소':act==='arrival'?'내원확인':act==='complete'?'진료완료':'예약확정',goodoc:'저장 완료 (모의)',chart:chartResult,patient:'상태 안내 발송 (모의)',pending},...old]);
    setBusy(false);setDialog({type:'detail',id:r.id});notify(`${state} 처리했습니다. 실제 서버·차트·환자에게는 반영되지 않습니다.`);
  };
const retry=(log:Log)=>{if(serverDown){notify('서버 연결을 먼저 복구해 주세요.');return;}if(logs.find(l=>l.record===log.record)?.id!==log.id){setLogs(old=>old.map(l=>l.id===log.id?{...l,chart:'이후 상태 변경 · 재전달 안 함',pending:false}:l));notify('이후 상태가 변경되어 이전 이벤트는 다시 보내지 않습니다.');return;}if(log.action==='내원확인'){const result='현재 차트 상태 확인 필요 · 자동 재전달 안 함';setLogs(old=>old.map(l=>l.id===log.id?{...l,chart:result,pending:false}:l));setRows(old=>old.map(r=>r.id===log.record?{...r,delivery:result}:r));notify('내원확인은 자동 재전달하지 않습니다. 실제 차트의 현재 상태 확인이 필요합니다.');return;}if(!linked||!bridge||!online){notify('차트 연결을 먼저 복구해 주세요.');return;}setLogs(old=>old.map(l=>l.id===log.id?{...l,chart:'전달·응답 확인 (모의)',pending:false}:l));setRows(old=>old.map(r=>r.id===log.record?{...r,delivery:'전달·응답 확인 (모의)'}:r));notify('차트 전달을 다시 확인했습니다. 환자 안내는 중복 발송하지 않습니다.');};
  const install=async()=>{setInstalling(true);await new Promise(resolve=>setTimeout(resolve,900));setBridge(true);setOnline(true);setInstalling(false);notify('브릿지 연결을 모의 완료했습니다. 실제 파일은 설치되지 않았습니다.');};
  const reset=()=>{setRows(BASE.map(x=>({...x})));setLinked(false);setBridge(false);setOnline(true);setServerDown(false);setLogs([]);setShowLogs(false);setFailure(false);setStateFilter('전체 상태');setClosed(false);setMaximized(false);setChart('K차트');setRooms([{name:'1진료실',doctor:'김○○ 원장',active:true},{name:'2진료실',doctor:'박○○ 원장',active:true}]);setItems([{name:'독감 백신',price:'35,000원',category:'예방접종',active:true},{name:'가다실 9가',price:'210,000원',category:'예방접종',active:true},{name:'싱그릭스',price:'230,000원',category:'예방접종',active:true}]);setAutoConfirm(false);setSmart(true);setIntervalValue('30');clearFilters();changeMode(false);notify('모든 가상 데이터를 초기화했습니다.');};
  const rowActions=(r:RecordItem)=><div className="cu-actions">{toBe&&r.kind!=='진료항목 예약'&&r.state==='내원예정'&&r.date===TODAY&&<button onClick={e=>{e.stopPropagation();action(r,'arrival');}}>내원확인</button>}{r.state==='확정대기'&&<button onClick={e=>{e.stopPropagation();action(r,'confirm');}}>확정</button>}{['내원예정','진료대기중'].includes(r.state)&&<button onClick={e=>{e.stopPropagation();action(r,'complete');}}>완료</button>}{MUTABLE.includes(r.state)&&<button className="danger-text" onClick={e=>{e.stopPropagation();openCancel(r);}}>취소</button>}<button aria-label={`${r.id} 상세 보기`} onClick={e=>{e.stopPropagation();setDialog({type:'detail',id:r.id});}}><VscChevronRight/></button></div>;
  const connection=linked?(bridge?(online?'차트 연결됨':'차트 연결 끊김'):'브릿지 연결 필요'):'차트 비연동';
  return <div className={'cu-app '+(maximized?'maximized':'')}>
    <div className="cu-prototype"><div><strong>커넥트 통합 시뮬레이터</strong><span>가상 데이터 · 실제 저장 없음</span></div><div className="cu-proto-actions"><div className="cu-segment" role="group" aria-label="화면 비교"><button aria-pressed={!toBe} className={!toBe?'selected':''} onClick={()=>changeMode(false)}>As-is · 현재</button><button aria-pressed={toBe} className={toBe?'selected':''} onClick={()=>{setStateFilter('전체 상태');changeMode(true);}}>To-be · 통합안</button></div><button className="cu-btn quiet" onClick={()=>setShowLogs(!showLogs)}><VscHistory/>처리 로그{logs.length>0&&` ${logs.length}`}</button><button className="cu-icon" onClick={reset} aria-label="시뮬레이터 초기화"><VscRefresh/></button></div></div>
    {toBe&&<div className="cu-planned"><VscInfo/>미승인 통합안 미리보기 · 설치, 차트 전달, 환자 알림은 시뮬레이션입니다. 출시 일정 미정.</div>}
    {!closed?<div className="cn-screen cu-client">
      <div className="cn-titlebar cu-titlebar"><div className="cu-brand"><img src={LOGO} alt="굿닥"/><span>커넥트</span></div><div className="cu-window-actions"><button className="cu-icon" onClick={()=>setDialog({type:'settings'})} aria-label="프로그램 환경설정"><VscSettingsGear/></button><button className="cu-icon" onClick={()=>{setClosed(true);notify('트레이의 커넥트 아이콘으로 다시 열 수 있어요.');}} aria-label="최소화"><VscChromeMinimize/></button><button className="cu-icon" onClick={()=>setMaximized(!maximized)} aria-label={maximized?'이전 크기로':'최대화'}>{maximized?<VscChromeRestore/>:<VscChromeMaximize/>}</button><button className="cu-icon close" onClick={()=>setClosed(true)} aria-label="창 닫기"><VscChromeClose/></button></div></div>
      <div className="cu-body">
        <aside className="cn-nav cu-nav" aria-label={toBe?'웹 업무 메뉴':'기존 커넥트 메뉴'}>
          <div className="cu-hospital"><strong>굿닥 예시의원</strong><span>화면 검토용 병원</span></div>
          <div className="cu-nav-section">서비스 운영</div>
          {toBe?NAV.map((n,i)=><button key={n} className={'cu-nav-row '+(menu===n?'active':'')} onClick={()=>go(n)}>{i===0?<VscDashboard/>:i===1?<VscListFlat/>:i===4?<VscSettingsGear/>:<VscCalendar/>}<span>{n}</span></button>):<><button className="cu-nav-row" onClick={()=>setDialog({type:'notice',title:'차트 접수·예약'})}><span>차트 접수·예약</span><VscChevronRight/></button><div className="cu-nav-row">비급여 예약 <small>beta</small><VscChevronDown/></div>{[['진료 현황','예약 신청 내역'],['진료항목','진료항목 관리'],['진료실 운영 설정','운영 설정']].map(([n,label])=><button key={n} className={'cu-nav-row indent '+(menu===n?'active':'')} onClick={()=>go(n)}>{label}</button>)}</>}
          <div className="cu-nav-section">병원 홍보</div><button className="cu-nav-row" onClick={()=>setDialog({type:'notice',title:'병원 검색 정보'})}><span>병원 검색 정보</span><VscChevronRight/></button><button className="cu-nav-row" onClick={()=>setDialog({type:'notice',title:'병원 소식 알림'})}><span>병원 소식 알림</span><VscChevronRight/></button>
          <div className="cu-nav-section">외부 플랫폼 연동</div><button className="cu-nav-row" onClick={()=>setDialog({type:'notice',title:'카카오톡 예약하기'})}><span>카카오톡 예약하기</span><VscChevronRight/></button>
          <div className="cu-nav-bottom"><span>{toBe?'업무 화면 · 웹':'기존 메뉴 · 클라이언트'}</span><button onClick={()=>setDialog({type:'guide'})}>이용가이드</button></div>
        </aside>
        <main className="cn-main cu-main">
          <header className="cn-header cu-header"><div><h1 className="cn-title">{!toBe&&menu==='진료 현황'?'예약 신청 내역':!toBe&&menu==='진료실 운영 설정'?'진료 예약 설정':menu}</h1><p className="cn-desc">{menu==='대시보드'?'오늘 우리 병원의 신청·진료 현황과 공지사항을 확인할 수 있어요.':menu==='진료 현황'?(toBe?'접수, 진료실 예약, 진료항목 예약을 한곳에서 확인하고 처리할 수 있어요.':'진료항목 예약 신청과 내원 예정 일정을 확인하고 처리할 수 있어요.'):menu==='진료항목'?'굿닥에 노출되는 우리 병원 진료항목과 가격 정보를 관리할 수 있어요.':menu==='진료실 관리'?'진료실과 담당 의료진, 운영 여부를 관리할 수 있어요.':'우리 병원의 진료 예약 운영 방식을 설정할 수 있어요.'}</p></div>{['진료실 관리','진료항목'].includes(menu)?<button className="cu-btn primary" onClick={()=>{setFormName('');setFormDoctor('');setFormPrice('');setDialog({type:menu==='진료항목'?'item':'room'});}}><VscAdd/>{menu==='진료항목'?'새 진료항목':'새 진료실'}</button>:<button className="cu-btn quiet" onClick={()=>notify('가상 데이터로 새로고침했습니다. 실제 서버 조회는 하지 않습니다.')}><VscRefresh/>새로고침</button>}</header>
          {serverDown&&<div className="cu-warning"><VscWarning/>서버 연결을 확인할 수 없습니다. 마지막 조회 정보이며 상태 변경을 저장할 수 없습니다.</div>}
          <div className="cu-content">
          {menu==='대시보드'&&<><div className="cu-section-heading"><h2>오늘 현황</h2><span>2026.10.02 (금) · 예시 집계</span></div><div className="cu-stat-grid">{[['예약 신청',rows.filter(r=>r.date===TODAY&&r.kind!=='접수').length,'전체'],['진료 완료',rows.filter(r=>r.date===TODAY&&r.state==='진료완료').length,'진료완료'],['진료 취소',rows.filter(r=>r.date===TODAY&&['병원취소','환자취소'].includes(r.state)).length,'지난 내역']].map(([label,count,target])=><button className="cu-stat" key={label} onClick={()=>{go('진료 현황',String(target));setDate('오늘');if(label==='예약 신청')setKind('예약 전체');if(target==='진료완료')setStateFilter('진료완료');}}><span>{label}</span><strong>{count}<small>건</small></strong><VscChevronRight/></button>)}</div><p className="cu-subnote">지표 구성은 기존 데스크 기준입니다. 숫자는 가상 내역으로 만든 예시이며 실제 집계 규격 검증 전입니다.</p><div className="cu-section-heading notice"><h2>공지사항</h2><button className="cu-btn quiet" onClick={()=>setDialog({type:'guide'})}>이용가이드 <VscArrowRight/></button></div><div className="cu-notice-list">{['통합 진료 현황 화면을 확인해 주세요','차트 연결 상태 확인 방법','진료항목 예약 운영 안내'].map((n,i)=><button key={n} onClick={()=>setDialog({type:'notice',title:n})}><span><span className="cu-notice-type">안내</span>{n}</span><span>2026.10.0{2-i%2}<VscChevronRight/></span></button>)}</div></>}
          {menu==='진료 현황'&&<>
            <div className="cu-tabs" role="tablist" aria-label="진료 상태">{tabs.map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'active':''} onClick={()=>{setTab(t);setStateFilter('전체 상태');}}>{t}<span>{source.filter(r=>inTab(r,t)).length}</span></button>)}</div>
            <div className="cu-filters"><label className="cu-search"><VscSearch/><input aria-label="진료내역 검색" placeholder="환자명, 연락처, 진료항목 검색" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="조회 기간" value={date} onChange={e=>setDate(e.target.value)}><option>전체 기간</option><option>오늘</option></select>{toBe&&<><select aria-label="신청 유형" value={kind} onChange={e=>setKind(e.target.value)}><option>전체 유형</option><option>예약 전체</option><option>접수</option><option>진료실 예약</option><option>진료항목 예약</option></select><select aria-label="진료실 필터" value={room} onChange={e=>setRoom(e.target.value)}><option>전체 진료실</option>{rooms.map(r=><option key={r.name}>{r.name}</option>)}</select></>}<button className="cu-icon" aria-label="검색 조건 초기화" onClick={clearFilters}><VscRefresh/></button></div>
            <div className="cu-table-toolbar"><span>총 <strong>{list.length}</strong>건{toBe&&tab==='처리 필요'&&<small>확정대기·예약실패는 완료 처리와 구분합니다.</small>}</span><div>{toBe&&<select aria-label="상세 상태" value={stateFilter} onChange={e=>{setStateFilter(e.target.value);setPage(1);}}><option>전체 상태</option><option>확정대기</option>{STATES.map(s=><option key={s}>{s}</option>)}<option>자동 종료</option></select>}<select aria-label="정렬" value={sort} onChange={e=>setSort(e.target.value)}><option>가까운 방문일시 순</option><option>최근 방문일시 순</option><option>환자명 순</option></select></div></div>
            <div className="cu-table-wrap"><table className="cu-table"><thead><tr><th>상태</th><th>방문일시{!toBe&&' / 신청일시'}</th>{toBe&&<th>유형 / 진료실</th>}<th>진료항목 / 가격옵션</th><th>환자 / 연락처</th><th>처리</th></tr></thead><tbody>{list.slice((currentPage-1)*7,currentPage*7).map(r=><tr key={r.id} tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')setDialog({type:'detail',id:r.id});}} onClick={()=>setDialog({type:'detail',id:r.id})}><td><Tag state={r.state}/>{r.delivery?.includes('대기')&&<small className="cu-delivery">차트 전달 대기</small>}</td><td><strong>{r.date.replaceAll('-','.')} {r.time}</strong><small>{!toBe?`신청 ${r.date<'2026-10-01'?'2026.09.28':'2026.10.01'} 17:20`:r.id}</small></td>{toBe&&<td>{r.kind}<small>{r.room}</small></td>}<td><strong>{r.item}</strong><small>{r.price}</small></td><td><strong>{r.name}</strong><small>{r.phone}</small></td><td>{rowActions(r)}</td></tr>)}</tbody></table>{!list.length&&<div className="cu-empty"><VscSearch/><strong>조건에 맞는 내역이 없어요</strong><button className="cu-btn" onClick={()=>{clearFilters();setTab(toBe?'전체':'예약 신청');}}>전체 내역 보기</button></div>}</div>
            <div className="cu-pagination"><span>7개씩 보기</span><div><button disabled={currentPage===1} onClick={()=>setPage(currentPage-1)} aria-label="이전 페이지">‹</button>{Array.from({length:pageCount},(_,i)=><button key={i} className={currentPage===i+1?'active':''} onClick={()=>setPage(i+1)}>{i+1}</button>)}<button disabled={currentPage===pageCount} onClick={()=>setPage(currentPage+1)} aria-label="다음 페이지">›</button></div></div>
          </>}
          {menu==='진료실 관리'&&<div className="cu-management"><table className="cu-table"><thead><tr><th>진료실</th><th>담당 의료진</th><th>운영 상태</th><th>관리</th></tr></thead><tbody>{rooms.map((r,i)=><tr key={r.name}><td><strong>{r.name}</strong></td><td>{r.doctor}</td><td><button className={'cu-toggle '+(r.active?'on':'')} aria-label={`${r.name} 운영`} aria-pressed={r.active} onClick={()=>{setRooms(old=>old.map((x,j)=>j===i?{...x,active:!x.active}:x));notify('운영 여부를 가상 저장했습니다.');}}><span/></button></td><td><button className="cu-btn quiet" onClick={()=>{setFormName(r.name);setFormDoctor(r.doctor);setDialog({type:'room',index:i});}}>상세 / 수정 <VscChevronRight/></button></td></tr>)}</tbody></table></div>}
          {menu==='진료항목'&&<div className="cu-item-panel"><div className="cu-item-categories"><strong>카테고리</strong><button className="active">예방접종 <span>{items.length}</span></button></div><div className="cu-item-list"><h3>예방접종</h3>{items.map((r,i)=><div className="cu-item-row" key={r.name}><button onClick={()=>{setFormName(r.name);setFormPrice(r.price);setDialog({type:'item',index:i});}}><strong>{r.name}</strong><small>{r.price}</small></button><span className={r.active?'cu-blue':'cu-muted'}>{r.active?'노출중':'미노출'}</span><button className={'cu-toggle '+(r.active?'on':'')} aria-label={`${r.name} 굿닥 노출`} aria-pressed={r.active} onClick={()=>setItems(old=>old.map((x,j)=>j===i?{...x,active:!x.active}:x))}><span/></button><VscChevronRight/></div>)}</div></div>}
          {menu==='진료실 운영 설정'&&toBe&&<div className="cu-settings-page"><h2>{toBe?'진료실 예약 운영':'진료 예약 운영'}</h2><div className="cu-setting-row"><div><strong>예약 자동 확정</strong><p>신청된 예약을 병원 확인 없이 자동으로 확정합니다.</p></div><button className={'cu-toggle '+(autoConfirm?'on':'')} aria-label="예약 자동 확정" aria-pressed={autoConfirm} onClick={()=>{setAutoConfirm(!autoConfirm);notify('설정을 가상 저장했습니다.');}}><span/></button></div><div className="cu-setting-row"><div><strong>스마트접수</strong><p>예약 시간에 맞춰 접수를 진행합니다.</p></div><button className={'cu-toggle '+(smart?'on':'')} aria-label="스마트접수" aria-pressed={smart} onClick={()=>setSmart(!smart)}><span/></button></div><div className="cu-setting-row"><div><strong>접수 시작 간격</strong><p>예약 시간 전 접수를 시작하는 간격입니다.</p></div><label><input type="number" min="0" max="360" aria-label="접수 시작 간격" value={interval} onChange={e=>setIntervalValue(e.target.value)}/> 분</label></div><button className="cu-btn primary" onClick={()=>Number(interval)>=0&&Number(interval)<=360?notify('운영 설정을 가상 저장했습니다.'):notify('예시 입력 범위 0~360분을 확인해 주세요.')}>저장</button><p className="cu-subnote">기존 운영 설정의 화면 재현입니다. 차트별 실제 지원 범위는 이 시안으로 확정하지 않습니다.</p></div>}
          {menu==='진료실 운영 설정'&&!toBe&&<div className="cu-settings-page"><div className="cu-setting-row"><div><strong>진료 예약 받기</strong><p>{items.length}개의 진료항목이 등록되어 있어요.</p></div><button className={'cu-toggle '+(apptUsed?'on':'')} aria-label="진료 예약 받기" aria-pressed={apptUsed} onClick={()=>setApptUsed(!apptUsed)}><span/></button></div><h2 style={{marginTop:32}}>설정</h2><p className="cu-inline-note">병원 운영 시간에 맞춰 30분 단위로 예약을 받습니다.</p>{[['예약 자동 확정','자동 확정 사용 시, 별도 승인 없이 예약 신청과 동시에 자동으로 확정됩니다.',autoConfirm,setAutoConfirm],['당일 예약 허용','당일 예약 허용 시, 현재 시간 기준 1시간 이후부터 당일 예약을 받습니다.',sameDay,setSameDay],['새 예약 알림 받기','새 예약 신청이 발생하면, 이 PC에서 윈도우 알림을 받습니다.',newNotice,setNewNotice]].map(([label,description,value,setValue])=><div className="cu-setting-row" key={String(label)}><div><strong>{String(label)}</strong><p>{String(description)}</p></div><button className={'cu-toggle '+(value?'on':'')} aria-label={String(label)} aria-pressed={Boolean(value)} onClick={()=>{(setValue as React.Dispatch<React.SetStateAction<boolean>>)(!value);notify('설정을 가상 저장했습니다.');}}><span/></button></div>)}<p className="cu-subnote">현재 화면 재현 · 외부 플랫폼 미연동 예시. 실제 설정은 변경되지 않습니다.</p></div>}
          </div>
        </main>
      </div>
      <div className="cu-statusbar"><span><span className={'cu-dot '+(linked&&!online?'warn':'')}/>{connection}</span><span>{toBe?'웹 업무 화면':'기존 커넥트 화면 재현'} · 데이터 기준: 가상 예시</span><button onClick={()=>setShowLogs(!showLogs)}><VscHistory/>처리 로그</button></div>
    </div>:<div className="cu-closed"><VscDeviceDesktop/><h2>커넥트가 트레이에 있습니다</h2><p>아래 트레이 아이콘으로 다시 열거나 환경설정에 접근하세요.</p><button className="cu-btn primary" onClick={()=>setClosed(false)}>커넥트 열기</button></div>}
    <div className="cu-taskbar"><span>Windows 트레이 · 시뮬레이션</span><div><label><input type="checkbox" checked={serverDown} onChange={e=>setServerDown(e.target.checked)}/>서버 오류 테스트</label><button className="cu-tray-icon" aria-label="커넥트 트레이 메뉴" aria-expanded={tray} onClick={()=>setTray(!tray)}><img src={LOGO} alt=""/><VscChevronDown/></button><span>09:41<br/>2026-10-02</span></div>{tray&&<div className="cu-tray-menu"><button onClick={()=>{setClosed(false);setTray(false);}}>커넥트 열기</button><button onClick={()=>{setDialog({type:'settings'});setTray(false);}}><VscSettingsGear/>환경설정</button><hr/><button onClick={()=>{setClosed(true);setTray(false);}}>창 닫기</button></div>}</div>
{showLogs&&<aside className="cu-log" aria-label="모의 처리 로그"><header><div><h2>처리 로그</h2><p>굿닥 상태와 차트 결과를 구분합니다.</p></div><button className="cu-icon" aria-label="처리 로그 닫기" onClick={()=>setShowLogs(false)}><VscChromeClose/></button></header>{!logs.length?<div className="cu-empty"><VscHistory/><strong>아직 처리한 내역이 없어요</strong><p>To-be에서 내원확인·취소·완료를 눌러보세요.</p></div>:logs.map(l=><div className="cu-log-card" key={l.id}><strong>{l.record} · {l.action}</strong><dl><dt>굿닥</dt><dd>{l.goodoc}</dd><dt>차트</dt><dd className={l.pending?'cu-orange':''}>{l.chart}</dd><dt>환자 안내</dt><dd>{l.patient}</dd></dl>{l.pending&&<button className="cu-btn" onClick={()=>retry(l)}>{l.action==='내원확인'?'처리 결과 확인':'차트 전달 재시도'}</button>}</div>)}</aside>}
    {toast&&<div className="cu-toast" role="status"><VscCheck/>{toast}</div>}
    {dialog?.type==='detail'&&chosen&&<Modal title="진료 내역 상세" wide onClose={()=>setDialog(null)} footer={<><button className="cu-btn" onClick={()=>setDialog(null)}>닫기</button>{MUTABLE.includes(chosen.state)&&rowActions(chosen)}</>}><div className="cu-detail-heading"><span>{chosen.kind} · {chosen.id}</span><Tag state={chosen.state}/></div><h3 className="cu-detail-label">방문 예정 / 신청 일시</h3><div className="cu-detail-card"><strong className="cu-detail-date">{chosen.date.replaceAll('-','.')} {chosen.time}</strong><p>신청 {chosen.date<'2026-10-01'?'2026.09.28':'2026.10.01'} 17:20</p></div><h3 className="cu-detail-label">{chosen.kind==='진료항목 예약'?'예약 진료항목':'진료 정보'}</h3><div className="cu-detail-card"><strong>{chosen.item}</strong><p>{chosen.price} · {chosen.room==='—'?'진료실 미지정':chosen.room}</p></div><h3 className="cu-detail-label">환자 정보</h3><div className="cu-detail-card cu-person"><div><span>환자</span><strong>{chosen.name}</strong></div><div><span>연락처</span><strong>{chosen.phone}</strong></div></div>{chosen.reason&&<><h3 className="cu-detail-label">처리 사유</h3><div className="cu-detail-card">{chosen.reason}</div></>}{chosen.state==='자동 종료'&&<p className="cu-inline-note"><VscInfo/>자동 종료는 실제 진료완료·취소가 아닙니다. 상태 변경 액션을 제공하지 않습니다.</p>}{toBe&&<><h3 className="cu-detail-label">차트 전달</h3><div className="cu-detail-card">{chosen.delivery||(chosen.kind==='진료항목 예약'?'해당 없음 · 진료항목 예약은 별도 관리':linked?connection:'차트 비연동 · 굿닥에서 관리')}<p>굿닥 상태와 차트 반영 결과는 별도로 확인합니다.</p></div></>}</Modal>}
{dialog?.type==='cancel'&&chosen&&<Modal title="예약 취소 사유를 선택해 주세요" busy={busy} onClose={()=>setDialog(null)} footer={<><button className="cu-btn" disabled={busy} onClick={()=>setDialog(null)}>취소</button><button className="cu-btn danger" disabled={busy||(reason==='직접 입력'&&!memo.trim())} onClick={execute}>{busy?'처리 중…':'확인'}</button></>}><p className="cu-cancel-context">{chosen.name} · {chosen.item}<br/>{chosen.date} {chosen.time}</p><div className="cu-radio-list">{[...REASONS,...(toBe?['직접 입력']:[])].map(s=><label key={s}><input name="reason" type="radio" value={s} checked={reason===s} onChange={()=>setReason(s)}/>{s}</label>)}</div>{reason==='직접 입력'&&<><textarea aria-label="취소 안내 문구" placeholder="취소 사유를 입력해 주세요. 실제 개인정보는 입력하지 마세요." maxLength={200} value={memo} onChange={e=>setMemo(e.target.value)}/><p className="cu-subnote">{memo.length}/200 · 검토용 입력 제한</p></>}<p className="cu-inline-note"><VscBell/>취소 상태 안내는 모의 발송됩니다. 입력 사유의 환자 공개 범위는 별도 정책 검토 대상입니다.</p>{toBe&&<label className="cu-test-option"><input type="checkbox" checked={failure} onChange={e=>setFailure(e.target.checked)}/>이번 저장 실패 테스트</label>}{error&&<><p className="cu-error" role="alert">{error}</p>{serverDown&&<button className="cu-btn" onClick={()=>{setServerDown(false);setError('');notify('서버 연결을 모의 복구했습니다. 입력은 유지됩니다.');}}>모의 서버 연결 복구</button>}</>}</Modal>}
    {dialog?.type==='action'&&chosen&&<Modal title={dialog.action==='arrival'?'내원확인 처리할까요?':dialog.action==='complete'?'진료완료 처리할까요?':'예약을 확정할까요?'} busy={busy} onClose={()=>setDialog(null)} footer={<><button className="cu-btn" disabled={busy} onClick={()=>setDialog(null)}>취소</button><button className="cu-btn primary" disabled={busy} onClick={execute}>{busy?'처리 중…':'확인'}</button></>}><div className="cu-detail-card"><strong>{chosen.name} · {chosen.kind}</strong><p>{chosen.item} / {chosen.date} {chosen.time}</p></div><p>{dialog.action==='arrival'?'내원 상태를 확인하고 진료 대기중으로 표시합니다.':dialog.action==='complete'?'병원이 실제 진료가 끝났음을 확인한 뒤 처리합니다.':'신청된 일정을 예약 확정 상태로 표시합니다.'}</p>{linked&&chosen.kind!=='진료항목 예약'&&<p className="cu-inline-note"><VscInfo/>{dialog.action!=='arrival'?'해당 상태 변경의 차트 전달 규격은 확인 필요합니다. 이 시안에서는 굿닥 상태만 바꾸고 차트 요청은 보류합니다.':online&&bridge?'차트 전달 및 응답 확인을 모사합니다.':'차트 연결이 끊겨 있어 전달 대기로 구분합니다.'}</p>}{error&&<><p className="cu-error" role="alert">{error}</p>{serverDown&&<button className="cu-btn" onClick={()=>{setServerDown(false);setError('');notify('서버 연결을 모의 복구했습니다. 입력은 유지됩니다.');}}>모의 서버 연결 복구</button>}</>}</Modal>}
    {dialog?.type==='settings'&&<Modal title="프로그램 환경설정" onClose={()=>setDialog(null)} busy={installing} footer={<button className="cu-btn primary" disabled={installing} onClick={()=>{setDialog(null);notify('환경설정을 이 시뮬레이터에 적용했습니다.');}}>적용</button>}><div className="cu-setting-row"><div><strong>차트 연동 사용</strong><p>기본값은 비연동입니다. 웹 업무는 그대로 사용할 수 있어요.</p></div><button className={'cu-toggle '+(linked?'on':'')} aria-label="차트 연동 사용" aria-pressed={linked} disabled={installing} onClick={()=>setLinked(!linked)}><span/></button></div>{linked?<><label className="cu-form-label">사용 중인 차트<select aria-label="사용 중인 차트" value={chart} disabled={installing} onChange={e=>{setChart(e.target.value);setBridge(false);}}><option>K차트</option><option>연동 차트 예시</option></select></label><label className="cu-form-label">차트 설치 경로<input aria-label="차트 설치 경로" value={chart==='K차트'?'C:\\ChartExample\\KChart':'C:\\ChartExample\\Chart'} readOnly/></label><p className="cu-subnote">경로는 예시입니다. 실제 경로 탐색·파일 설치·권한 변경은 하지 않습니다.</p><div className="cu-bridge"><VscDeviceDesktop/><div><strong>{installing?'브릿지 설치·연결 확인 중…':bridge?'브릿지 설치됨 (모의)':'브릿지 설치가 필요해요'}</strong><p>{bridge?connection:'차트를 선택한 뒤 해당 경로에 연결하는 과정을 모사합니다.'}</p></div><button className="cu-btn" disabled={installing} onClick={install}>{installing?'연결 중…':bridge?'연결 확인':'설치 및 연결'}</button></div>{bridge&&<button className="cu-btn" onClick={()=>setOnline(!online)}><VscDebugDisconnect/>{online?'차트 연결 끊김 테스트':'차트 연결 복구'}</button>}</>:<div className="cu-inline-note"><VscInfo/>비연동 모드 · 굿닥의 접수·예약을 관리하며 차트로 이벤트를 보내지 않습니다.</div>}<p className="cu-subnote">프로그램 환경설정은 웹 좌측 메뉴가 아닌 커넥트 트레이에서 엽니다.</p></Modal>}
    {(dialog?.type==='room'||dialog?.type==='item')&&<Modal title={dialog.type==='room'?'진료실 정보':'진료항목 정보'} onClose={()=>setDialog(null)} footer={<><button className="cu-btn" onClick={()=>setDialog(null)}>취소</button><button className="cu-btn primary" disabled={!formName.trim()} onClick={()=>{if(dialog.type==='room'){const entry={name:formName.trim(),doctor:formDoctor.trim()||'담당 의료진 미지정',active:true};setRooms(old=>dialog.index===undefined?[...old,entry]:old.map((r,i)=>i===dialog.index?{...r,...entry}:r));}else{const entry={name:formName.trim(),price:formPrice.trim()||'상담 후 결정',category:'예방접종',active:true};setItems(old=>dialog.index===undefined?[...old,entry]:old.map((r,i)=>i===dialog.index?{...r,...entry}:r));}setDialog(null);notify('정보를 가상 저장했습니다.');}}>저장</button></>}><label className="cu-form-label">{dialog.type==='room'?'진료실 이름':'진료항목 이름'}<input aria-label="관리 항목 이름" value={formName} onChange={e=>setFormName(e.target.value)}/></label><label className="cu-form-label">{dialog.type==='room'?'담당 의료진':'가격 정보'}<input aria-label="관리 항목 정보" value={dialog.type==='room'?formDoctor:formPrice} onChange={e=>dialog.type==='room'?setFormDoctor(e.target.value):setFormPrice(e.target.value)}/></label><p className="cu-subnote">기존 메뉴의 위치와 관리 흐름을 확인하는 축약 재현입니다. 상세 정책은 변경하지 않습니다.</p></Modal>}
    {(dialog?.type==='notice'||dialog?.type==='guide')&&<Modal title={dialog.title||'통합 커넥트 이용가이드'} onClose={()=>setDialog(null)} footer={<button className="cu-btn primary" onClick={()=>setDialog(null)}>확인</button>}>{dialog.type==='guide'?<ol className="cu-guide"><li>상단에서 <strong>To-be · 통합안</strong>을 선택합니다.</li><li><strong>진료 현황</strong>에서 유형·상태별로 신청을 찾습니다.</li><li>행을 눌러 상세를 열고 내원확인·취소·완료를 체험합니다.</li><li>하단 <strong>트레이 아이콘 → 환경설정</strong>에서 차트를 선택하고 연결을 모사합니다.</li><li><strong>처리 로그</strong>에서 굿닥·차트·환자 안내 결과를 따로 확인합니다.</li></ol>:<><p>기존 메뉴의 위치와 진입점을 보존한 화면입니다.</p><p>이 시뮬레이터에서는 통합 진료 현황·대시보드·환경설정 흐름을 중심으로 검토합니다. 다른 운영 페이지와 외부 연동은 실제로 열거나 변경하지 않습니다.</p></>}<p className="cu-subnote">가상 검토용 · 실제 환자정보를 입력하지 마세요.</p></Modal>}
  </div>;
}
